import type { Locale } from "@/lib/i18n";

export type ContactCountry = {
  key: string;
  label: string;
  email: string;
};

const UK_IRELAND = "naomi.cuff@mersen.com";
const NETHERLANDS = "sunil.ramsoedit@mersen.com";
const BELGIUM_LUX = "fabien.buisseret@mersen.com";
const FRANCE = "nordine.souar@mersen.com";
const ITALY = "stefano.paolini@mersen.com";
const SPAIN = "almudena.herranz@mersen.com";
const PORTUGAL = "sergio.jimenez@mersen.com";
const NORDICS_BALTICS = "afshin.pourarsalan@mersen.com";
const FINLAND = "ville.honka@mersen.com";
const GERMANY = "torsten.frank@mersen.com";
const OTHER = "karoly.galle@mersen.com";

// Every sovereign state of Europe, each mapped to its own contact.
// Countries not covered by a named contact route to OTHER.
const COUNTRIES: {
  key: string;
  email: string;
  en: string;
  fr: string;
  it: string;
  de: string;
  nl: string;
  hu: string;
  pt: string;
  pl: string;
}[] = [
  {
    key: "albania",
    email: OTHER,
    en: "Albania",
    fr: "Albanie",
    it: "Albania",
    de: "Albanien",
    nl: "Albanië",
    hu: "Albánia",
    pt: "Albânia",
    pl: "Albania",
  },
  {
    key: "andorra",
    email: OTHER,
    en: "Andorra",
    fr: "Andorre",
    it: "Andorra",
    de: "Andorra",
    nl: "Andorra",
    hu: "Andorra",
    pt: "Andorra",
    pl: "Andora",
  },
  {
    key: "austria",
    email: OTHER,
    en: "Austria",
    fr: "Autriche",
    it: "Austria",
    de: "Österreich",
    nl: "Oostenrijk",
    hu: "Ausztria",
    pt: "Áustria",
    pl: "Austria",
  },
  {
    key: "belarus",
    email: OTHER,
    en: "Belarus",
    fr: "Biélorussie",
    it: "Bielorussia",
    de: "Belarus",
    nl: "Wit-Rusland",
    hu: "Fehéroroszország",
    pt: "Bielorrússia",
    pl: "Białoruś",
  },
  {
    key: "belgium",
    email: BELGIUM_LUX,
    en: "Belgium",
    fr: "Belgique",
    it: "Belgio",
    de: "Belgien",
    nl: "België",
    hu: "Belgium",
    pt: "Bélgica",
    pl: "Belgia",
  },
  {
    key: "bosnia-herzegovina",
    email: OTHER,
    en: "Bosnia and Herzegovina",
    fr: "Bosnie-Herzégovine",
    it: "Bosnia ed Erzegovina",
    de: "Bosnien und Herzegowina",
    nl: "Bosnië en Herzegovina",
    hu: "Bosznia-Hercegovina",
    pt: "Bósnia e Herzegovina",
    pl: "Bośnia i Hercegowina",
  },
  {
    key: "bulgaria",
    email: OTHER,
    en: "Bulgaria",
    fr: "Bulgarie",
    it: "Bulgaria",
    de: "Bulgarien",
    nl: "Bulgarije",
    hu: "Bulgária",
    pt: "Bulgária",
    pl: "Bułgaria",
  },
  {
    key: "croatia",
    email: OTHER,
    en: "Croatia",
    fr: "Croatie",
    it: "Croazia",
    de: "Kroatien",
    nl: "Kroatië",
    hu: "Horvátország",
    pt: "Croácia",
    pl: "Chorwacja",
  },
  {
    key: "cyprus",
    email: OTHER,
    en: "Cyprus",
    fr: "Chypre",
    it: "Cipro",
    de: "Zypern",
    nl: "Cyprus",
    hu: "Ciprus",
    pt: "Chipre",
    pl: "Cypr",
  },
  {
    key: "czech-republic",
    email: OTHER,
    en: "Czech Republic",
    fr: "République tchèque",
    it: "Repubblica Ceca",
    de: "Tschechien",
    nl: "Tsjechië",
    hu: "Csehország",
    pt: "República Checa",
    pl: "Czechy",
  },
  {
    key: "denmark",
    email: NORDICS_BALTICS,
    en: "Denmark",
    fr: "Danemark",
    it: "Danimarca",
    de: "Dänemark",
    nl: "Denemarken",
    hu: "Dánia",
    pt: "Dinamarca",
    pl: "Dania",
  },
  {
    key: "estonia",
    email: NORDICS_BALTICS,
    en: "Estonia",
    fr: "Estonie",
    it: "Estonia",
    de: "Estland",
    nl: "Estland",
    hu: "Észtország",
    pt: "Estónia",
    pl: "Estonia",
  },
  {
    key: "finland",
    email: FINLAND,
    en: "Finland",
    fr: "Finlande",
    it: "Finlandia",
    de: "Finnland",
    nl: "Finland",
    hu: "Finnország",
    pt: "Finlândia",
    pl: "Finlandia",
  },
  {
    key: "france",
    email: FRANCE,
    en: "France",
    fr: "France",
    it: "Francia",
    de: "Frankreich",
    nl: "Frankrijk",
    hu: "Franciaország",
    pt: "França",
    pl: "Francja",
  },
  {
    key: "germany",
    email: GERMANY,
    en: "Germany",
    fr: "Allemagne",
    it: "Germania",
    de: "Deutschland",
    nl: "Duitsland",
    hu: "Németország",
    pt: "Alemanha",
    pl: "Niemcy",
  },
  {
    key: "greece",
    email: OTHER,
    en: "Greece",
    fr: "Grèce",
    it: "Grecia",
    de: "Griechenland",
    nl: "Griekenland",
    hu: "Görögország",
    pt: "Grécia",
    pl: "Grecja",
  },
  {
    key: "hungary",
    email: OTHER,
    en: "Hungary",
    fr: "Hongrie",
    it: "Ungheria",
    de: "Ungarn",
    nl: "Hongarije",
    hu: "Magyarország",
    pt: "Hungria",
    pl: "Węgry",
  },
  {
    key: "iceland",
    email: NORDICS_BALTICS,
    en: "Iceland",
    fr: "Islande",
    it: "Islanda",
    de: "Island",
    nl: "IJsland",
    hu: "Izland",
    pt: "Islândia",
    pl: "Islandia",
  },
  {
    key: "ireland",
    email: UK_IRELAND,
    en: "Ireland",
    fr: "Irlande",
    it: "Irlanda",
    de: "Irland",
    nl: "Ierland",
    hu: "Írország",
    pt: "Irlanda",
    pl: "Irlandia",
  },
  {
    key: "italy",
    email: ITALY,
    en: "Italy",
    fr: "Italie",
    it: "Italia",
    de: "Italien",
    nl: "Italië",
    hu: "Olaszország",
    pt: "Itália",
    pl: "Włochy",
  },
  {
    key: "kosovo",
    email: OTHER,
    en: "Kosovo",
    fr: "Kosovo",
    it: "Kosovo",
    de: "Kosovo",
    nl: "Kosovo",
    hu: "Koszovó",
    pt: "Kosovo",
    pl: "Kosowo",
  },
  {
    key: "latvia",
    email: NORDICS_BALTICS,
    en: "Latvia",
    fr: "Lettonie",
    it: "Lettonia",
    de: "Lettland",
    nl: "Letland",
    hu: "Lettország",
    pt: "Letónia",
    pl: "Łotwa",
  },
  {
    key: "liechtenstein",
    email: OTHER,
    en: "Liechtenstein",
    fr: "Liechtenstein",
    it: "Liechtenstein",
    de: "Liechtenstein",
    nl: "Liechtenstein",
    hu: "Liechtenstein",
    pt: "Liechtenstein",
    pl: "Liechtenstein",
  },
  {
    key: "lithuania",
    email: NORDICS_BALTICS,
    en: "Lithuania",
    fr: "Lituanie",
    it: "Lituania",
    de: "Litauen",
    nl: "Litouwen",
    hu: "Litvánia",
    pt: "Lituânia",
    pl: "Litwa",
  },
  {
    key: "luxembourg",
    email: BELGIUM_LUX,
    en: "Luxembourg",
    fr: "Luxembourg",
    it: "Lussemburgo",
    de: "Luxemburg",
    nl: "Luxemburg",
    hu: "Luxemburg",
    pt: "Luxemburgo",
    pl: "Luksemburg",
  },
  {
    key: "malta",
    email: OTHER,
    en: "Malta",
    fr: "Malte",
    it: "Malta",
    de: "Malta",
    nl: "Malta",
    hu: "Málta",
    pt: "Malta",
    pl: "Malta",
  },
  {
    key: "moldova",
    email: OTHER,
    en: "Moldova",
    fr: "Moldavie",
    it: "Moldavia",
    de: "Republik Moldau",
    nl: "Moldavië",
    hu: "Moldova",
    pt: "Moldávia",
    pl: "Mołdawia",
  },
  {
    key: "monaco",
    email: OTHER,
    en: "Monaco",
    fr: "Monaco",
    it: "Monaco",
    de: "Monaco",
    nl: "Monaco",
    hu: "Monaco",
    pt: "Mónaco",
    pl: "Monako",
  },
  {
    key: "montenegro",
    email: OTHER,
    en: "Montenegro",
    fr: "Monténégro",
    it: "Montenegro",
    de: "Montenegro",
    nl: "Montenegro",
    hu: "Montenegró",
    pt: "Montenegro",
    pl: "Czarnogóra",
  },
  {
    key: "netherlands",
    email: NETHERLANDS,
    en: "Netherlands",
    fr: "Pays-Bas",
    it: "Paesi Bassi",
    de: "Niederlande",
    nl: "Nederland",
    hu: "Hollandia",
    pt: "Países Baixos",
    pl: "Holandia",
  },
  {
    key: "north-macedonia",
    email: OTHER,
    en: "North Macedonia",
    fr: "Macédoine du Nord",
    it: "Macedonia del Nord",
    de: "Nordmazedonien",
    nl: "Noord-Macedonië",
    hu: "Észak-Macedónia",
    pt: "Macedónia do Norte",
    pl: "Macedonia Północna",
  },
  {
    key: "norway",
    email: NORDICS_BALTICS,
    en: "Norway",
    fr: "Norvège",
    it: "Norvegia",
    de: "Norwegen",
    nl: "Noorwegen",
    hu: "Norvégia",
    pt: "Noruega",
    pl: "Norwegia",
  },
  {
    key: "poland",
    email: OTHER,
    en: "Poland",
    fr: "Pologne",
    it: "Polonia",
    de: "Polen",
    nl: "Polen",
    hu: "Lengyelország",
    pt: "Polónia",
    pl: "Polska",
  },
  {
    key: "portugal",
    email: PORTUGAL,
    en: "Portugal",
    fr: "Portugal",
    it: "Portogallo",
    de: "Portugal",
    nl: "Portugal",
    hu: "Portugália",
    pt: "Portugal",
    pl: "Portugalia",
  },
  {
    key: "romania",
    email: OTHER,
    en: "Romania",
    fr: "Roumanie",
    it: "Romania",
    de: "Rumänien",
    nl: "Roemenië",
    hu: "Románia",
    pt: "Roménia",
    pl: "Rumunia",
  },
  {
    key: "russia",
    email: OTHER,
    en: "Russia",
    fr: "Russie",
    it: "Russia",
    de: "Russland",
    nl: "Rusland",
    hu: "Oroszország",
    pt: "Rússia",
    pl: "Rosja",
  },
  {
    key: "san-marino",
    email: OTHER,
    en: "San Marino",
    fr: "Saint-Marin",
    it: "San Marino",
    de: "San Marino",
    nl: "San Marino",
    hu: "San Marino",
    pt: "São Marino",
    pl: "San Marino",
  },
  {
    key: "serbia",
    email: OTHER,
    en: "Serbia",
    fr: "Serbie",
    it: "Serbia",
    de: "Serbien",
    nl: "Servië",
    hu: "Szerbia",
    pt: "Sérvia",
    pl: "Serbia",
  },
  {
    key: "slovakia",
    email: OTHER,
    en: "Slovakia",
    fr: "Slovaquie",
    it: "Slovacchia",
    de: "Slowakei",
    nl: "Slowakije",
    hu: "Szlovákia",
    pt: "Eslováquia",
    pl: "Słowacja",
  },
  {
    key: "slovenia",
    email: OTHER,
    en: "Slovenia",
    fr: "Slovénie",
    it: "Slovenia",
    de: "Slowenien",
    nl: "Slovenië",
    hu: "Szlovénia",
    pt: "Eslovénia",
    pl: "Słowenia",
  },
  {
    key: "spain",
    email: SPAIN,
    en: "Spain",
    fr: "Espagne",
    it: "Spagna",
    de: "Spanien",
    nl: "Spanje",
    hu: "Spanyolország",
    pt: "Espanha",
    pl: "Hiszpania",
  },
  {
    key: "sweden",
    email: NORDICS_BALTICS,
    en: "Sweden",
    fr: "Suède",
    it: "Svezia",
    de: "Schweden",
    nl: "Zweden",
    hu: "Svédország",
    pt: "Suécia",
    pl: "Szwecja",
  },
  {
    key: "switzerland",
    email: OTHER,
    en: "Switzerland",
    fr: "Suisse",
    it: "Svizzera",
    de: "Schweiz",
    nl: "Zwitserland",
    hu: "Svájc",
    pt: "Suíça",
    pl: "Szwajcaria",
  },
  {
    key: "ukraine",
    email: OTHER,
    en: "Ukraine",
    fr: "Ukraine",
    it: "Ucraina",
    de: "Ukraine",
    nl: "Oekraïne",
    hu: "Ukrajna",
    pt: "Ucrânia",
    pl: "Ukraina",
  },
  {
    key: "united-kingdom",
    email: UK_IRELAND,
    en: "United Kingdom",
    fr: "Royaume-Uni",
    it: "Regno Unito",
    de: "Vereinigtes Königreich",
    nl: "Verenigd Koninkrijk",
    hu: "Egyesült Királyság",
    pt: "Reino Unido",
    pl: "Wielka Brytania",
  },
  {
    key: "vatican-city",
    email: OTHER,
    en: "Vatican City",
    fr: "Cité du Vatican",
    it: "Città del Vaticano",
    de: "Vatikanstadt",
    nl: "Vaticaanstad",
    hu: "Vatikán",
    pt: "Cidade do Vaticano",
    pl: "Watykan",
  },
];

export function getContactCountries(locale: Locale): ContactCountry[] {
  return COUNTRIES.map((c) => ({
    key: c.key,
    email: c.email,
    label: c[locale],
  })).sort((a, b) => a.label.localeCompare(b.label, locale));
}
